CREATE TABLE T_LINK_ROLE_RESOURCE (
  LRR_ID CHAR(32) NOT NULL CONSTRAINT PK_T_LINK_ROLE_RESOURCE PRIMARY KEY,
  ROLE_ID CHAR(32),
  RESOURCE_ID CHAR(32),
  TENANT_ID CHAR(32),
  STATUS NUMBER(2),
  APPROVAL_STATUS NUMBER(2),
  CREATE_TIME TIMESTAMP,
  MODIFY_TIME TIMESTAMP,
  CREATE_USER CHAR(32),
  MODIFY_USER CHAR(32),
  SHOW_ORDER NUMBER(4),
  UNIT_ID CHAR(32)
);

CREATE TABLE T_LINK_ROLECLASSIFICATION_UNIT (
  LRU_ID CHAR(32) NOT NULL CONSTRAINT PK_T_LINK_ROLE_UNIT PRIMARY KEY,
  ROLECLASSIFICATION_ID CHAR(32),
  UNIT_ID CHAR(32),
  CREATE_TIME TIMESTAMP,
  MODIFY_TIME TIMESTAMP,
  CREATE_USER CHAR(32),
  MODIFY_USER CHAR(32),
  STATUS NUMBER(2),
  APPROVAL_STATUS NUMBER(2),
  SHOW_ORDER NUMBER(2),
  TENANT_ID CHAR(32)
); 