CREATE TABLE T_LINK_POOL_UNIT (
  LPU_ID CHAR(32) NOT NULL CONSTRAINT PK_T_LINK_POOL_UNIT PRIMARY KEY,
  CREATE_TIME TIMESTAMP,
  CREATE_USER CHAR(32),
  PARENT_ID CHAR(32),
  COMMENTS VARCHAR2(255),
  TENANT_ID CHAR(32),
  MODIFY_USER CHAR(32),
  MODIFY_TIME TIMESTAMP,
  SHOW_ORDER NUMBER(4),
  STATUS NUMBER(2),
  RESOURCE_POOL_ID CHAR(32),
  UNIT CHAR(32)
); 
CREATE TABLE T_LINK_RESOURCE_POOL (
  LRP_ID CHAR(32) NOT NULL CONSTRAINT PK_T_LINK_RESOURCE_POOL PRIMARY KEY,
  CREATE_TIME TIMESTAMP,
  CREATE_USER CHAR(32),
  MODIFY_TIME TIMESTAMP,
  MODIFY_USER CHAR(32),
  COMMENTS VARCHAR2(255),
  SHOW_ORDER NUMBER(4),
  STATUS NUMBER(2),
  RESOURCE_POOL_ID CHAR(32),
  RESOURCE_ID CHAR(32),
  PARENT_ID CHAR(32),
  TENANT_ID CHAR(32)
); 
CREATE TABLE T_RESOURCE_POOL (
  RP_ID CHAR(32) NOT NULL CONSTRAINT PK_T_RESOURCE_POOL PRIMARY KEY,
  CREATE_TIME TIMESTAMP,
  CREATE_USER CHAR(32),
  PARENT_ID CHAR(32),
  COMMENTS VARCHAR2(255),
  TENANT_ID CHAR(32),
  MODIFY_USER CHAR(32),
  MODIFY_TIME TIMESTAMP,
  SHOW_ORDER NUMBER(4),
  STATUS NUMBER(2),
  NAME VARCHAR2(255)
);